// public

//---------------------------------------------------------------------------
//
// Project: MCS_USB_LIB
// Copyright (c) 2007 Multi Channel Systems. All rights reserved
//
// $Header: /MCS_USB_Lib/DLL/MCS_USB_def.h 94    13.07.12 13:18 Jesinger $
// $Modtime: 13.07.12 8:37 $
//
//---------------------------------------------------------------------------

/*! \file
  \brief Constants needed by MCS_USB_lib.dll
 */


#ifndef _MCS_USB_DEF_H_ 
#define _MCS_USB_DEF_H_


/***************************************************************
 *                    
 *  Include File to be shared between embedded devices and Windows
 *
 ***************************************************************/

/* Firmware destinations */

#define MCSUSB_DEST_UNKNOWN  -1

#define MCSUSB_DEST_DSP       0x00
#define MCSUSB_DEST_USB       0x01
#define MCSUSB_DEST_MCU1      0x02
#define MCSUSB_DEST_USB_RAM   0x03
#define MCSUSB_DEST_BOOTSTRAP 0x10
#define MCSUSB_DEST_BOOTSTAP_OTHER_CYPRESS 0x11
#define MCSUSB_DEST_ALTERA    0x40
#define MCSUSB_DEST_FPGA2     0x41
#define MCSUSB_DEST_FPGA3     0x42
#define MCSUSB_DEST_FPGA4     0x43
#define MCSUSB_DEST_FPGA5     0x44
#define MCSUSB_DEST_FPGA6     0x45
#define MCSUSB_DEST_FPGA7     0x46
#define MCSUSB_DEST_FPGA8     0x47
#define MCSUSB_DEST_FPGA9     0x48
#define MCSUSB_DEST_FPGA10    0x49
#define MCSUSB_DEST_FPGA11    0x4A
#define MCSUSB_DEST_FPGA12    0x4B
#define MCSUSB_DEST_FPGA13    0x4C
#define MCSUSB_DEST_FPGA14    0x4D
#define MCSUSB_DEST_FPGA15    0x4E
#define MCSUSB_DEST_FPGA16    0x4F
#define MCSUSB_DEST_MCSBUS1   0x60
#define MCSUSB_DEST_MCSBUS2   0x61
#define MCSUSB_DEST_MCSBUS3   0x62
#define MCSUSB_DEST_MCSBUS4   0x63
#define MCSUSB_DEST_MCSBUS5   0x64
#define MCSUSB_DEST_MCSBUS6   0x65
#define MCSUSB_DEST_MCSBUS7   0x66
#define MCSUSB_DEST_MCSBUS8   0x67
#define MCSUSB_DEST_MCSBUS9   0x68
#define MCSUSB_DEST_MCSBUS10   0x69
#define MCSUSB_DEST_MCSBUS11   0x6A
#define MCSUSB_DEST_MCSBUS12   0x6B
#define MCSUSB_DEST_MCSBUS13   0x6C
#define MCSUSB_DEST_MCSBUS14   0x6D
#define MCSUSB_DEST_MCSBUS15   0x6E
#define MCSUSB_DEST_MCSBUS0   0x6F
#define MCSUSB_DEST_PIC       0x82
#define MCSUSB_DEST_PIC2      0x83
#define MCSUSB_DEST_PIC3      0x84
#define MCSUSB_DEST_PIC4      0x85
#define MCSUSB_DEST_PIC5      0x86
#define MCSUSB_DEST_PIC6      0x87
#define MCSUSB_DEST_PIC7      0x88
#define MCSUSB_DEST_PIC8      0x89
#define MCSUSB_DEST_CHANNELPIC 0x88
// 0x89 reserved
// 0x8A reserved
// 0x8B reserved
// 0x8C reserved
// 0x8D reserved
// 0x8E reserved
// 0x8F reserved
#define MCSUSB_DEST_CHANNELSEC 0x90
// 0x91 reserved
// 0x92 reserved
// 0x93 reserved
// 0x94 reserved
// 0x95 reserved
// 0x96 reserved
// 0x97 reserved

#define	MCSUSB_DEST_TIMESLOT0  0x000
#define	MCSUSB_DEST_BUSNUMBER0 0x000
#define MCSUSB_DEST_BUS0_MCSBUS1 (MCSUSB_DEST_MCSBUS1 | MCSUSB_DEST_BUSNUMBER0)
#define MCSUSB_DEST_BUS0_MCSBUS2 (MCSUSB_DEST_MCSBUS2 | MCSUSB_DEST_BUSNUMBER0)
#define MCSUSB_DEST_BUS0_MCSBUS3 (MCSUSB_DEST_MCSBUS3 | MCSUSB_DEST_BUSNUMBER0)
#define MCSUSB_DEST_BUS0_MCSBUS4 (MCSUSB_DEST_MCSBUS4 | MCSUSB_DEST_BUSNUMBER0)
#define MCSUSB_DEST_BUS0_MCSBUS5 (MCSUSB_DEST_MCSBUS5 | MCSUSB_DEST_BUSNUMBER0)
#define MCSUSB_DEST_BUS0_MCSBUS6 (MCSUSB_DEST_MCSBUS6 | MCSUSB_DEST_BUSNUMBER0)
#define MCSUSB_DEST_BUS0_MCSBUS7 (MCSUSB_DEST_MCSBUS7 | MCSUSB_DEST_BUSNUMBER0)
#define MCSUSB_DEST_BUS0_MCSBUS8 (MCSUSB_DEST_MCSBUS8 | MCSUSB_DEST_BUSNUMBER0)
#define MCSUSB_DEST_BUS0_MCSBUS9 (MCSUSB_DEST_MCSBUS9 | MCSUSB_DEST_BUSNUMBER0)
#define MCSUSB_DEST_BUS0_MCSBUS10 (MCSUSB_DEST_MCSBUS10 | MCSUSB_DEST_BUSNUMBER0)
#define MCSUSB_DEST_BUS0_MCSBUS11 (MCSUSB_DEST_MCSBUS11 | MCSUSB_DEST_BUSNUMBER0)
#define MCSUSB_DEST_BUS0_MCSBUS12 (MCSUSB_DEST_MCSBUS12 | MCSUSB_DEST_BUSNUMBER0)
#define MCSUSB_DEST_BUS0_MCSBUS13 (MCSUSB_DEST_MCSBUS13 | MCSUSB_DEST_BUSNUMBER0)
#define MCSUSB_DEST_BUS0_MCSBUS14 (MCSUSB_DEST_MCSBUS14 | MCSUSB_DEST_BUSNUMBER0)
#define MCSUSB_DEST_BUS0_MCSBUS15 (MCSUSB_DEST_MCSBUS15 | MCSUSB_DEST_BUSNUMBER0)
#define MCSUSB_DEST_BUS0_MCSBUS0 (MCSUSB_DEST_MCSBUS0 | MCSUSB_DEST_BUSNUMBER0)

#define	MCSUSB_DEST_TIMESLOT1  0x100
#define XILINX_DEST_GOLDEN     0x100
#define	MCSUSB_DEST_BUSNUMBER1 0x100
#define MCSUSB_DEST_BUS1_MCSBUS1 (MCSUSB_DEST_MCSBUS1 | MCSUSB_DEST_BUSNUMBER1)
#define MCSUSB_DEST_BUS1_MCSBUS2 (MCSUSB_DEST_MCSBUS2 | MCSUSB_DEST_BUSNUMBER1)
#define MCSUSB_DEST_BUS1_MCSBUS3 (MCSUSB_DEST_MCSBUS3 | MCSUSB_DEST_BUSNUMBER1)
#define MCSUSB_DEST_BUS1_MCSBUS4 (MCSUSB_DEST_MCSBUS4 | MCSUSB_DEST_BUSNUMBER1)
#define MCSUSB_DEST_BUS1_MCSBUS5 (MCSUSB_DEST_MCSBUS5 | MCSUSB_DEST_BUSNUMBER1)
#define MCSUSB_DEST_BUS1_MCSBUS6 (MCSUSB_DEST_MCSBUS6 | MCSUSB_DEST_BUSNUMBER1)
#define MCSUSB_DEST_BUS1_MCSBUS7 (MCSUSB_DEST_MCSBUS7 | MCSUSB_DEST_BUSNUMBER1)
#define MCSUSB_DEST_BUS1_MCSBUS8 (MCSUSB_DEST_MCSBUS8 | MCSUSB_DEST_BUSNUMBER1)
#define MCSUSB_DEST_BUS1_MCSBUS9 (MCSUSB_DEST_MCSBUS9 | MCSUSB_DEST_BUSNUMBER1)
#define MCSUSB_DEST_BUS1_MCSBUS10 (MCSUSB_DEST_MCSBUS10 | MCSUSB_DEST_BUSNUMBER1)
#define MCSUSB_DEST_BUS1_MCSBUS11 (MCSUSB_DEST_MCSBUS11 | MCSUSB_DEST_BUSNUMBER1)
#define MCSUSB_DEST_BUS1_MCSBUS12 (MCSUSB_DEST_MCSBUS12 | MCSUSB_DEST_BUSNUMBER1)
#define MCSUSB_DEST_BUS1_MCSBUS13 (MCSUSB_DEST_MCSBUS13 | MCSUSB_DEST_BUSNUMBER1)
#define MCSUSB_DEST_BUS1_MCSBUS14 (MCSUSB_DEST_MCSBUS14 | MCSUSB_DEST_BUSNUMBER1)
#define MCSUSB_DEST_BUS1_MCSBUS15 (MCSUSB_DEST_MCSBUS15 | MCSUSB_DEST_BUSNUMBER1)
#define MCSUSB_DEST_BUS1_MCSBUS0 (MCSUSB_DEST_MCSBUS0 | MCSUSB_DEST_BUSNUMBER1)

#define	MCSUSB_DEST_TIMESLOT2  0x200
#define XILINX_DEST_BASEIMAGE  0x200
#define	MCSUSB_DEST_BUSNUMBER2 0x200
#define MCSUSB_DEST_BUS2_MCSBUS1 (MCSUSB_DEST_MCSBUS1 | MCSUSB_DEST_BUSNUMBER2)
#define MCSUSB_DEST_BUS2_MCSBUS2 (MCSUSB_DEST_MCSBUS2 | MCSUSB_DEST_BUSNUMBER2)
#define MCSUSB_DEST_BUS2_MCSBUS3 (MCSUSB_DEST_MCSBUS3 | MCSUSB_DEST_BUSNUMBER2)
#define MCSUSB_DEST_BUS2_MCSBUS4 (MCSUSB_DEST_MCSBUS4 | MCSUSB_DEST_BUSNUMBER2)
#define MCSUSB_DEST_BUS2_MCSBUS5 (MCSUSB_DEST_MCSBUS5 | MCSUSB_DEST_BUSNUMBER2)
#define MCSUSB_DEST_BUS2_MCSBUS6 (MCSUSB_DEST_MCSBUS6 | MCSUSB_DEST_BUSNUMBER2)
#define MCSUSB_DEST_BUS2_MCSBUS7 (MCSUSB_DEST_MCSBUS7 | MCSUSB_DEST_BUSNUMBER2)
#define MCSUSB_DEST_BUS2_MCSBUS8 (MCSUSB_DEST_MCSBUS8 | MCSUSB_DEST_BUSNUMBER2)
#define MCSUSB_DEST_BUS2_MCSBUS9 (MCSUSB_DEST_MCSBUS9 | MCSUSB_DEST_BUSNUMBER2)
#define MCSUSB_DEST_BUS2_MCSBUS10 (MCSUSB_DEST_MCSBUS10 | MCSUSB_DEST_BUSNUMBER2)
#define MCSUSB_DEST_BUS2_MCSBUS11 (MCSUSB_DEST_MCSBUS11 | MCSUSB_DEST_BUSNUMBER2)
#define MCSUSB_DEST_BUS2_MCSBUS12 (MCSUSB_DEST_MCSBUS12 | MCSUSB_DEST_BUSNUMBER2)
#define MCSUSB_DEST_BUS2_MCSBUS13 (MCSUSB_DEST_MCSBUS13 | MCSUSB_DEST_BUSNUMBER2)
#define MCSUSB_DEST_BUS2_MCSBUS14 (MCSUSB_DEST_MCSBUS14 | MCSUSB_DEST_BUSNUMBER2)
#define MCSUSB_DEST_BUS2_MCSBUS15 (MCSUSB_DEST_MCSBUS15 | MCSUSB_DEST_BUSNUMBER2)
#define MCSUSB_DEST_BUS2_MCSBUS0 (MCSUSB_DEST_MCSBUS0 | MCSUSB_DEST_BUSNUMBER2)

#define	MCSUSB_DEST_TIMESLOT3  0x300
#define XILINX_DEST_BOOTSTRAP  0x300
#define	MCSUSB_DEST_BUSNUMBER3 0x300
#define MCSUSB_DEST_BUS3_MCSBUS1 (MCSUSB_DEST_MCSBUS1 | MCSUSB_DEST_BUSNUMBER3)
#define MCSUSB_DEST_BUS3_MCSBUS2 (MCSUSB_DEST_MCSBUS2 | MCSUSB_DEST_BUSNUMBER3)
#define MCSUSB_DEST_BUS3_MCSBUS3 (MCSUSB_DEST_MCSBUS3 | MCSUSB_DEST_BUSNUMBER3)
#define MCSUSB_DEST_BUS3_MCSBUS4 (MCSUSB_DEST_MCSBUS4 | MCSUSB_DEST_BUSNUMBER3)
#define MCSUSB_DEST_BUS3_MCSBUS5 (MCSUSB_DEST_MCSBUS5 | MCSUSB_DEST_BUSNUMBER3)
#define MCSUSB_DEST_BUS3_MCSBUS6 (MCSUSB_DEST_MCSBUS6 | MCSUSB_DEST_BUSNUMBER3)
#define MCSUSB_DEST_BUS3_MCSBUS7 (MCSUSB_DEST_MCSBUS7 | MCSUSB_DEST_BUSNUMBER3)
#define MCSUSB_DEST_BUS3_MCSBUS8 (MCSUSB_DEST_MCSBUS8 | MCSUSB_DEST_BUSNUMBER3)
#define MCSUSB_DEST_BUS3_MCSBUS9 (MCSUSB_DEST_MCSBUS9 | MCSUSB_DEST_BUSNUMBER3)
#define MCSUSB_DEST_BUS3_MCSBUS10 (MCSUSB_DEST_MCSBUS10 | MCSUSB_DEST_BUSNUMBER3)
#define MCSUSB_DEST_BUS3_MCSBUS11 (MCSUSB_DEST_MCSBUS11 | MCSUSB_DEST_BUSNUMBER3)
#define MCSUSB_DEST_BUS3_MCSBUS12 (MCSUSB_DEST_MCSBUS12 | MCSUSB_DEST_BUSNUMBER3)
#define MCSUSB_DEST_BUS3_MCSBUS13 (MCSUSB_DEST_MCSBUS13 | MCSUSB_DEST_BUSNUMBER3)
#define MCSUSB_DEST_BUS3_MCSBUS14 (MCSUSB_DEST_MCSBUS14 | MCSUSB_DEST_BUSNUMBER3)
#define MCSUSB_DEST_BUS3_MCSBUS15 (MCSUSB_DEST_MCSBUS15 | MCSUSB_DEST_BUSNUMBER3)
#define MCSUSB_DEST_BUS3_MCSBUS0 (MCSUSB_DEST_MCSBUS0 | MCSUSB_DEST_BUSNUMBER3)

#define	MCSUSB_DEST_BUSNUMBER4 0x400
#define MCSUSB_DEST_BUS4_MCSBUS1 (MCSUSB_DEST_MCSBUS1 | MCSUSB_DEST_BUSNUMBER4)
#define MCSUSB_DEST_BUS4_MCSBUS2 (MCSUSB_DEST_MCSBUS2 | MCSUSB_DEST_BUSNUMBER4)
#define MCSUSB_DEST_BUS4_MCSBUS3 (MCSUSB_DEST_MCSBUS3 | MCSUSB_DEST_BUSNUMBER4)
#define MCSUSB_DEST_BUS4_MCSBUS4 (MCSUSB_DEST_MCSBUS4 | MCSUSB_DEST_BUSNUMBER4)
#define MCSUSB_DEST_BUS4_MCSBUS5 (MCSUSB_DEST_MCSBUS5 | MCSUSB_DEST_BUSNUMBER4)
#define MCSUSB_DEST_BUS4_MCSBUS6 (MCSUSB_DEST_MCSBUS6 | MCSUSB_DEST_BUSNUMBER4)
#define MCSUSB_DEST_BUS4_MCSBUS7 (MCSUSB_DEST_MCSBUS7 | MCSUSB_DEST_BUSNUMBER4)
#define MCSUSB_DEST_BUS4_MCSBUS8 (MCSUSB_DEST_MCSBUS8 | MCSUSB_DEST_BUSNUMBER4)
#define MCSUSB_DEST_BUS4_MCSBUS9 (MCSUSB_DEST_MCSBUS9 | MCSUSB_DEST_BUSNUMBER4)
#define MCSUSB_DEST_BUS4_MCSBUS10 (MCSUSB_DEST_MCSBUS10 | MCSUSB_DEST_BUSNUMBER4)
#define MCSUSB_DEST_BUS4_MCSBUS11 (MCSUSB_DEST_MCSBUS11 | MCSUSB_DEST_BUSNUMBER4)
#define MCSUSB_DEST_BUS4_MCSBUS12 (MCSUSB_DEST_MCSBUS12 | MCSUSB_DEST_BUSNUMBER4)
#define MCSUSB_DEST_BUS4_MCSBUS13 (MCSUSB_DEST_MCSBUS13 | MCSUSB_DEST_BUSNUMBER4)
#define MCSUSB_DEST_BUS4_MCSBUS14 (MCSUSB_DEST_MCSBUS14 | MCSUSB_DEST_BUSNUMBER4)
#define MCSUSB_DEST_BUS4_MCSBUS15 (MCSUSB_DEST_MCSBUS15 | MCSUSB_DEST_BUSNUMBER4)
#define MCSUSB_DEST_BUS4_MCSBUS0 (MCSUSB_DEST_MCSBUS0 | MCSUSB_DEST_BUSNUMBER4)

#define	MCSUSB_DEST_BUSNUMBER5 0x500
#define MCSUSB_DEST_BUS5_MCSBUS1 (MCSUSB_DEST_MCSBUS1 | MCSUSB_DEST_BUSNUMBER5)
#define MCSUSB_DEST_BUS5_MCSBUS2 (MCSUSB_DEST_MCSBUS2 | MCSUSB_DEST_BUSNUMBER5)
#define MCSUSB_DEST_BUS5_MCSBUS3 (MCSUSB_DEST_MCSBUS3 | MCSUSB_DEST_BUSNUMBER5)
#define MCSUSB_DEST_BUS5_MCSBUS4 (MCSUSB_DEST_MCSBUS4 | MCSUSB_DEST_BUSNUMBER5)
#define MCSUSB_DEST_BUS5_MCSBUS5 (MCSUSB_DEST_MCSBUS5 | MCSUSB_DEST_BUSNUMBER5)
#define MCSUSB_DEST_BUS5_MCSBUS6 (MCSUSB_DEST_MCSBUS6 | MCSUSB_DEST_BUSNUMBER5)
#define MCSUSB_DEST_BUS5_MCSBUS7 (MCSUSB_DEST_MCSBUS7 | MCSUSB_DEST_BUSNUMBER5)
#define MCSUSB_DEST_BUS5_MCSBUS8 (MCSUSB_DEST_MCSBUS8 | MCSUSB_DEST_BUSNUMBER5)
#define MCSUSB_DEST_BUS5_MCSBUS9 (MCSUSB_DEST_MCSBUS9 | MCSUSB_DEST_BUSNUMBER5)
#define MCSUSB_DEST_BUS5_MCSBUS10 (MCSUSB_DEST_MCSBUS10 | MCSUSB_DEST_BUSNUMBER5)
#define MCSUSB_DEST_BUS5_MCSBUS11 (MCSUSB_DEST_MCSBUS11 | MCSUSB_DEST_BUSNUMBER5)
#define MCSUSB_DEST_BUS5_MCSBUS12 (MCSUSB_DEST_MCSBUS12 | MCSUSB_DEST_BUSNUMBER5)
#define MCSUSB_DEST_BUS5_MCSBUS13 (MCSUSB_DEST_MCSBUS13 | MCSUSB_DEST_BUSNUMBER5)
#define MCSUSB_DEST_BUS5_MCSBUS14 (MCSUSB_DEST_MCSBUS14 | MCSUSB_DEST_BUSNUMBER5)
#define MCSUSB_DEST_BUS5_MCSBUS15 (MCSUSB_DEST_MCSBUS15 | MCSUSB_DEST_BUSNUMBER5)
#define MCSUSB_DEST_BUS5_MCSBUS0 (MCSUSB_DEST_MCSBUS0 | MCSUSB_DEST_BUSNUMBER5)

#define	MCSUSB_DEST_BUSNUMBER6 0x600
#define MCSUSB_DEST_BUS6_MCSBUS1 (MCSUSB_DEST_MCSBUS1 | MCSUSB_DEST_BUSNUMBER6)
#define MCSUSB_DEST_BUS6_MCSBUS2 (MCSUSB_DEST_MCSBUS2 | MCSUSB_DEST_BUSNUMBER6)
#define MCSUSB_DEST_BUS6_MCSBUS3 (MCSUSB_DEST_MCSBUS3 | MCSUSB_DEST_BUSNUMBER6)
#define MCSUSB_DEST_BUS6_MCSBUS4 (MCSUSB_DEST_MCSBUS4 | MCSUSB_DEST_BUSNUMBER6)
#define MCSUSB_DEST_BUS6_MCSBUS5 (MCSUSB_DEST_MCSBUS5 | MCSUSB_DEST_BUSNUMBER6)
#define MCSUSB_DEST_BUS6_MCSBUS6 (MCSUSB_DEST_MCSBUS6 | MCSUSB_DEST_BUSNUMBER6)
#define MCSUSB_DEST_BUS6_MCSBUS7 (MCSUSB_DEST_MCSBUS7 | MCSUSB_DEST_BUSNUMBER6)
#define MCSUSB_DEST_BUS6_MCSBUS8 (MCSUSB_DEST_MCSBUS8 | MCSUSB_DEST_BUSNUMBER6)
#define MCSUSB_DEST_BUS6_MCSBUS9 (MCSUSB_DEST_MCSBUS9 | MCSUSB_DEST_BUSNUMBER6)
#define MCSUSB_DEST_BUS6_MCSBUS10 (MCSUSB_DEST_MCSBUS10 | MCSUSB_DEST_BUSNUMBER6)
#define MCSUSB_DEST_BUS6_MCSBUS11 (MCSUSB_DEST_MCSBUS11 | MCSUSB_DEST_BUSNUMBER6)
#define MCSUSB_DEST_BUS6_MCSBUS12 (MCSUSB_DEST_MCSBUS12 | MCSUSB_DEST_BUSNUMBER6)
#define MCSUSB_DEST_BUS6_MCSBUS13 (MCSUSB_DEST_MCSBUS13 | MCSUSB_DEST_BUSNUMBER6)
#define MCSUSB_DEST_BUS6_MCSBUS14 (MCSUSB_DEST_MCSBUS14 | MCSUSB_DEST_BUSNUMBER6)
#define MCSUSB_DEST_BUS6_MCSBUS15 (MCSUSB_DEST_MCSBUS15 | MCSUSB_DEST_BUSNUMBER6)
#define MCSUSB_DEST_BUS6_MCSBUS0 (MCSUSB_DEST_MCSBUS0 | MCSUSB_DEST_BUSNUMBER6)

#define	MCSUSB_DEST_BUSNUMBER7 0x700
#define MCSUSB_DEST_BUS7_MCSBUS1 (MCSUSB_DEST_MCSBUS1 | MCSUSB_DEST_BUSNUMBER7)
#define MCSUSB_DEST_BUS7_MCSBUS2 (MCSUSB_DEST_MCSBUS2 | MCSUSB_DEST_BUSNUMBER7)
#define MCSUSB_DEST_BUS7_MCSBUS3 (MCSUSB_DEST_MCSBUS3 | MCSUSB_DEST_BUSNUMBER7)
#define MCSUSB_DEST_BUS7_MCSBUS4 (MCSUSB_DEST_MCSBUS4 | MCSUSB_DEST_BUSNUMBER7)
#define MCSUSB_DEST_BUS7_MCSBUS5 (MCSUSB_DEST_MCSBUS5 | MCSUSB_DEST_BUSNUMBER7)
#define MCSUSB_DEST_BUS7_MCSBUS6 (MCSUSB_DEST_MCSBUS6 | MCSUSB_DEST_BUSNUMBER7)
#define MCSUSB_DEST_BUS7_MCSBUS7 (MCSUSB_DEST_MCSBUS7 | MCSUSB_DEST_BUSNUMBER7)
#define MCSUSB_DEST_BUS7_MCSBUS8 (MCSUSB_DEST_MCSBUS8 | MCSUSB_DEST_BUSNUMBER7)
#define MCSUSB_DEST_BUS7_MCSBUS9 (MCSUSB_DEST_MCSBUS9 | MCSUSB_DEST_BUSNUMBER7)
#define MCSUSB_DEST_BUS7_MCSBUS10 (MCSUSB_DEST_MCSBUS10 | MCSUSB_DEST_BUSNUMBER7)
#define MCSUSB_DEST_BUS7_MCSBUS11 (MCSUSB_DEST_MCSBUS11 | MCSUSB_DEST_BUSNUMBER7)
#define MCSUSB_DEST_BUS7_MCSBUS12 (MCSUSB_DEST_MCSBUS12 | MCSUSB_DEST_BUSNUMBER7)
#define MCSUSB_DEST_BUS7_MCSBUS13 (MCSUSB_DEST_MCSBUS13 | MCSUSB_DEST_BUSNUMBER7)
#define MCSUSB_DEST_BUS7_MCSBUS14 (MCSUSB_DEST_MCSBUS14 | MCSUSB_DEST_BUSNUMBER7)
#define MCSUSB_DEST_BUS7_MCSBUS15 (MCSUSB_DEST_MCSBUS15 | MCSUSB_DEST_BUSNUMBER7)
#define MCSUSB_DEST_BUS7_MCSBUS0 (MCSUSB_DEST_MCSBUS0 | MCSUSB_DEST_BUSNUMBER7)

#define FPGA_DEST_TARGET_MASK 0xf000
#define FX3_DEST_TARGET_MASK    0xff00

#define FLASH_DEST_TARGET1     0x1000
#define FLASH_DEST_TARGET2     0x2000
#define FLASH_DEST_TARGET3     0x3000
// the following are only used for the firmware list in IFB-Multiboot
#define FLASH_DEST_TARGET4     0x4000
#define FLASH_DEST_TARGET5     0x5000
#define FLASH_DEST_TARGET6     0x6000
#define FLASH_DEST_TARGET7     0x7000
#define FLASH_DEST_TARGET8     0x8000
#define FLASH_DEST_TARGET9     0x9000
#define FLASH_DEST_TARGET10    0xA000
#define FLASH_DEST_TARGET11    0xB000
#define FLASH_DEST_TARGET12    0xC000
#define FLASH_DEST_TARGET13    0xD000
#define FLASH_DEST_TARGET14    0xE000
#define FLASH_DEST_TARGET15    0xF000

#define MCSUSB_NAME_DSP       "DSP"
#define MCSUSB_NAME_USB       "USB"
#define MCSUSB_NAME_MCU1      "MCU1"
#define MCSUSB_NAME_BOOTSTRAP "Bootstrap"
#define MCSUSB_NAME_BOOTSTRAP_OTHER_CYPRESS "Bootstrap Other Usb"
#define MCSUSB_NAME_ALTERA    "Altera"
#define MCSUSB_NAME_FPGA2     "FPGA2"
#define MCSUSB_NAME_FPGA3     "FPGA3"
#define MCSUSB_NAME_FPGA4     "FPGA4"
#define MCSUSB_NAME_FPGA5     "FPGA5"
#define MCSUSB_NAME_FPGA6     "FPGA6"
#define MCSUSB_NAME_FPGA7     "FPGA7"
#define MCSUSB_NAME_FPGA8     "FPGA8"
#define MCSUSB_NAME_FPGA9     "FPGA9"
#define MCSUSB_NAME_FPGA10    "FPGA10"
#define MCSUSB_NAME_FPGA11    "FPGA11"
#define MCSUSB_NAME_FPGA12    "FPGA12"
#define MCSUSB_NAME_FPGA13    "FPGA13"
#define MCSUSB_NAME_FPGA14    "FPGA14"
#define MCSUSB_NAME_FPGA15    "FPGA15"
#define MCSUSB_NAME_FPGA16    "FPGA17"
#define MCSUSB_NAME_MCSBUS1   "McsBus1"
#define MCSUSB_NAME_MCSBUS2   "McsBus2"
#define MCSUSB_NAME_MCSBUS3   "McsBus3"
#define MCSUSB_NAME_MCSBUS4   "McsBus4"
#define MCSUSB_NAME_MCSBUS5   "McsBus5"
#define MCSUSB_NAME_MCSBUS6   "McsBus6"
#define MCSUSB_NAME_MCSBUS7   "McsBus7"
#define MCSUSB_NAME_MCSBUS8   "McsBus8"
#define MCSUSB_NAME_MCSBUS9   "McsBus9"
#define MCSUSB_NAME_MCSBUS10   "McsBus10"
#define MCSUSB_NAME_MCSBUS11   "McsBus11"
#define MCSUSB_NAME_MCSBUS12   "McsBus12"
#define MCSUSB_NAME_MCSBUS13   "McsBus13"
#define MCSUSB_NAME_MCSBUS14   "McsBus14"
#define MCSUSB_NAME_MCSBUS15   "McsBus15"
#define MCSUSB_NAME_MCSBUS0   "McsBus0"
#define MCSUSB_NAME_PIC       "PIC"
#define MCSUSB_NAME_PIC2      "PIC2"
#define MCSUSB_NAME_PIC3      "PIC3"
#define MCSUSB_NAME_PIC4      "PIC4"
#define MCSUSB_NAME_PIC5      "PIC5"
#define MCSUSB_NAME_PIC6      "PIC6"
#define MCSUSB_NAME_PIC7      "PIC7"
#define MCSUSB_NAME_PIC8      "PIC8"

#define MCSUSB_NAME_SCU_HS    "SCU_HS_0x.."

#define MCSUSB_NAME_BUS1_MCSBUS1 "Bus1McsBus1"
#define MCSUSB_NAME_BUS1_MCSBUS2 "Bus1McsBus2"
#define MCSUSB_NAME_BUS1_MCSBUS3 "Bus1McsBus3"
#define MCSUSB_NAME_BUS1_MCSBUS4 "Bus1McsBus4"
#define MCSUSB_NAME_BUS1_MCSBUS5 "Bus1McsBus5"
#define MCSUSB_NAME_BUS1_MCSBUS6 "Bus1McsBus6"
#define MCSUSB_NAME_BUS1_MCSBUS7 "Bus1McsBus7"
#define MCSUSB_NAME_BUS1_MCSBUS8 "Bus1McsBus8"
#define MCSUSB_NAME_BUS1_MCSBUS9 "Bus1McsBus9"
#define MCSUSB_NAME_BUS1_MCSBUS10 "Bus1McsBus10"
#define MCSUSB_NAME_BUS1_MCSBUS11 "Bus1McsBus11"
#define MCSUSB_NAME_BUS1_MCSBUS12 "Bus1McsBus12"
#define MCSUSB_NAME_BUS1_MCSBUS13 "Bus1McsBus13"
#define MCSUSB_NAME_BUS1_MCSBUS14 "Bus1McsBus14"
#define MCSUSB_NAME_BUS1_MCSBUS15 "Bus1McsBus15"
#define MCSUSB_NAME_BUS1_MCSBUS0 "Bus1McsBus0"

#define MCSUSB_NAME_BUS2_MCSBUS1 "Bus2McsBus1"
#define MCSUSB_NAME_BUS2_MCSBUS2 "Bus2McsBus2"
#define MCSUSB_NAME_BUS2_MCSBUS3 "Bus2McsBus3"
#define MCSUSB_NAME_BUS2_MCSBUS4 "Bus2McsBus4"
#define MCSUSB_NAME_BUS2_MCSBUS5 "Bus2McsBus5"
#define MCSUSB_NAME_BUS2_MCSBUS6 "Bus2McsBus6"
#define MCSUSB_NAME_BUS2_MCSBUS7 "Bus2McsBus7"
#define MCSUSB_NAME_BUS2_MCSBUS8 "Bus2McsBus8"
#define MCSUSB_NAME_BUS2_MCSBUS9 "Bus2McsBus9"
#define MCSUSB_NAME_BUS2_MCSBUS10 "Bus2McsBus10"
#define MCSUSB_NAME_BUS2_MCSBUS11 "Bus2McsBus11"
#define MCSUSB_NAME_BUS2_MCSBUS12 "Bus2McsBus12"
#define MCSUSB_NAME_BUS2_MCSBUS13 "Bus2McsBus13"
#define MCSUSB_NAME_BUS2_MCSBUS14 "Bus2McsBus14"
#define MCSUSB_NAME_BUS2_MCSBUS15 "Bus2McsBus15"
#define MCSUSB_NAME_BUS2_MCSBUS0 "Bus2McsBus0"

#define MCSUSB_NAME_BUS3_MCSBUS1 "Bus3McsBus1"
#define MCSUSB_NAME_BUS3_MCSBUS2 "Bus3McsBus2"
#define MCSUSB_NAME_BUS3_MCSBUS3 "Bus3McsBus3"
#define MCSUSB_NAME_BUS3_MCSBUS4 "Bus3McsBus4"
#define MCSUSB_NAME_BUS3_MCSBUS5 "Bus3McsBus5"
#define MCSUSB_NAME_BUS3_MCSBUS6 "Bus3McsBus6"
#define MCSUSB_NAME_BUS3_MCSBUS7 "Bus3McsBus7"
#define MCSUSB_NAME_BUS3_MCSBUS8 "Bus3McsBus8"
#define MCSUSB_NAME_BUS3_MCSBUS9 "Bus3McsBus9"
#define MCSUSB_NAME_BUS3_MCSBUS10 "Bus3McsBus10"
#define MCSUSB_NAME_BUS3_MCSBUS11 "Bus3McsBus11"
#define MCSUSB_NAME_BUS3_MCSBUS12 "Bus3McsBus12"
#define MCSUSB_NAME_BUS3_MCSBUS13 "Bus3McsBus13"
#define MCSUSB_NAME_BUS3_MCSBUS14 "Bus3McsBus14"
#define MCSUSB_NAME_BUS3_MCSBUS15 "Bus3McsBus15"
#define MCSUSB_NAME_BUS3_MCSBUS0 "Bus3McsBus0"

#define MCSUSB_NAME_BUS4_MCSBUS1 "Bus4McsBus1"
#define MCSUSB_NAME_BUS4_MCSBUS2 "Bus4McsBus2"
#define MCSUSB_NAME_BUS4_MCSBUS3 "Bus4McsBus3"
#define MCSUSB_NAME_BUS4_MCSBUS4 "Bus4McsBus4"
#define MCSUSB_NAME_BUS4_MCSBUS5 "Bus4McsBus5"
#define MCSUSB_NAME_BUS4_MCSBUS6 "Bus4McsBus6"
#define MCSUSB_NAME_BUS4_MCSBUS7 "Bus4McsBus7"
#define MCSUSB_NAME_BUS4_MCSBUS8 "Bus4McsBus8"
#define MCSUSB_NAME_BUS4_MCSBUS9 "Bus4McsBus9"
#define MCSUSB_NAME_BUS4_MCSBUS10 "Bus4McsBus10"
#define MCSUSB_NAME_BUS4_MCSBUS11 "Bus4McsBus11"
#define MCSUSB_NAME_BUS4_MCSBUS12 "Bus4McsBus12"
#define MCSUSB_NAME_BUS4_MCSBUS13 "Bus4McsBus13"
#define MCSUSB_NAME_BUS4_MCSBUS14 "Bus4McsBus14"
#define MCSUSB_NAME_BUS4_MCSBUS15 "Bus4McsBus15"
#define MCSUSB_NAME_BUS4_MCSBUS0 "Bus4McsBus0"

#define MCSUSB_NAME_BUS5_MCSBUS1 "Bus5McsBus1"
#define MCSUSB_NAME_BUS5_MCSBUS2 "Bus5McsBus2"
#define MCSUSB_NAME_BUS5_MCSBUS3 "Bus5McsBus3"
#define MCSUSB_NAME_BUS5_MCSBUS4 "Bus5McsBus4"
#define MCSUSB_NAME_BUS5_MCSBUS5 "Bus5McsBus5"
#define MCSUSB_NAME_BUS5_MCSBUS6 "Bus5McsBus6"
#define MCSUSB_NAME_BUS5_MCSBUS7 "Bus5McsBus7"
#define MCSUSB_NAME_BUS5_MCSBUS8 "Bus5McsBus8"
#define MCSUSB_NAME_BUS5_MCSBUS9 "Bus5McsBus9"
#define MCSUSB_NAME_BUS5_MCSBUS10 "Bus5McsBus10"
#define MCSUSB_NAME_BUS5_MCSBUS11 "Bus5McsBus11"
#define MCSUSB_NAME_BUS5_MCSBUS12 "Bus5McsBus12"
#define MCSUSB_NAME_BUS5_MCSBUS13 "Bus5McsBus13"
#define MCSUSB_NAME_BUS5_MCSBUS14 "Bus5McsBus14"
#define MCSUSB_NAME_BUS5_MCSBUS15 "Bus5McsBus15"
#define MCSUSB_NAME_BUS5_MCSBUS0 "Bus5McsBus0"

#define MCSUSB_NAME_BUS6_MCSBUS1 "Bus6McsBus1"
#define MCSUSB_NAME_BUS6_MCSBUS2 "Bus6McsBus2"
#define MCSUSB_NAME_BUS6_MCSBUS3 "Bus6McsBus3"
#define MCSUSB_NAME_BUS6_MCSBUS4 "Bus6McsBus4"
#define MCSUSB_NAME_BUS6_MCSBUS5 "Bus6McsBus5"
#define MCSUSB_NAME_BUS6_MCSBUS6 "Bus6McsBus6"
#define MCSUSB_NAME_BUS6_MCSBUS7 "Bus6McsBus7"
#define MCSUSB_NAME_BUS6_MCSBUS8 "Bus6McsBus8"
#define MCSUSB_NAME_BUS6_MCSBUS9 "Bus6McsBus9"
#define MCSUSB_NAME_BUS6_MCSBUS10 "Bus6McsBus10"
#define MCSUSB_NAME_BUS6_MCSBUS11 "Bus6McsBus11"
#define MCSUSB_NAME_BUS6_MCSBUS12 "Bus6McsBus12"
#define MCSUSB_NAME_BUS6_MCSBUS13 "Bus6McsBus13"
#define MCSUSB_NAME_BUS6_MCSBUS14 "Bus6McsBus14"
#define MCSUSB_NAME_BUS6_MCSBUS15 "Bus6McsBus15"
#define MCSUSB_NAME_BUS6_MCSBUS0 "Bus6McsBus0"

#define MCSUSB_NAME_BUS7_MCSBUS1 "Bus7McsBus1"
#define MCSUSB_NAME_BUS7_MCSBUS2 "Bus7McsBus2"
#define MCSUSB_NAME_BUS7_MCSBUS3 "Bus7McsBus3"
#define MCSUSB_NAME_BUS7_MCSBUS4 "Bus7McsBus4"
#define MCSUSB_NAME_BUS7_MCSBUS5 "Bus7McsBus5"
#define MCSUSB_NAME_BUS7_MCSBUS6 "Bus7McsBus6"
#define MCSUSB_NAME_BUS7_MCSBUS7 "Bus7McsBus7"
#define MCSUSB_NAME_BUS7_MCSBUS8 "Bus7McsBus8"
#define MCSUSB_NAME_BUS7_MCSBUS9 "Bus7McsBus9"
#define MCSUSB_NAME_BUS7_MCSBUS10 "Bus7McsBus10"
#define MCSUSB_NAME_BUS7_MCSBUS11 "Bus7McsBus11"
#define MCSUSB_NAME_BUS7_MCSBUS12 "Bus7McsBus12"
#define MCSUSB_NAME_BUS7_MCSBUS13 "Bus7McsBus13"
#define MCSUSB_NAME_BUS7_MCSBUS14 "Bus7McsBus14"
#define MCSUSB_NAME_BUS7_MCSBUS15 "Bus7McsBus15"
#define MCSUSB_NAME_BUS7_MCSBUS0 "Bus7McsBus0"

/************************************************************
*
* common for all devices
*
************************************************************/

#define MCS_USB_IDENT_LENGTH    100
#define MCS_USB_UL_BLOCKSIZE    256
#define MCS_USB_VERSION_LENGTH   32
#define MCS_USB_SERIAL_LENGTH    10


/*! \cond stg200x */
/***********************************************************************
 *
 * defines for the STG200x
 *
 ***********************************************************************/

//#define STG200x_BULK_OUT_EP  2

#define STG_MAX_NUM_CHANNELS 8
#define STG_MAX_NUM_SYNC_OUT 8
#define STG_MAX_NUM_TRIGGER  8
#define STG_EXTENDED_MAX_NUM_TRIGGER 32

//! max. number of stimulus channels
#define STG200x_NUM_CHANNELS   8
//! max. number of sync output channels
#define STG200x_NUM_SYNC_OUT   4

//! max. number of triggers
#define STG200x_NUM_TRIGGER    4

#define STG200x_MAX_SEGMENTS    100		// for STG200x
#define STG200x_MAX_SAMPLERATE  50000

#define STG_STREAM_MAGIC_NUMBER_START 0x7612
#define STG_STREAM_MAGIC_NUMBER_END   0xca7d
#define STG_STREAM_MAGIC_NUMBER_FEEDBACK 0x6a31de9a
#define STG_STREAM_BYTES_PER_SAMPLE_HIGHSPEED 32
#define STG_STREAM_BYTES_PER_SAMPLE_FULLSPEED (2*STG200x_NUM_CHANNELS)

#define STG200x_PROGINFO_LENGTH 512		// this is also the longest answer packet used so far
#define STG200x_DATA_BLOCKSIZE 2000

#define ADAPTER_TYPE_UNKOWN 9998
#define ADAPTER_TYPE_ENUM_NOT_APPLICABLE 9999


enum enSTG_ExtendedInterruptPipe {
	STG_ExIntPipe_None,          // reserved
	STG_ExIntPipe_ListIndex,
	MW_ExIntPipe_CurrentTemp,
	MW_ExIntPipe_PlateState,
	MW_ExIntPipe_SwitchState,
	STG_ExIntPipe_AdditionalTrigger,
    MCS_DeviceStatePush
};

#define MEA21_MAX_LISTMODE_ENTRIES 9
/*! \endcond */


#define FPGA_ID_NOT_CONNECTED                0x00000000
#define FPGA_ID_MEA2100_IF                   0x00000001
#define FPGA_ID_MEA2100_HS                   0x00000002
#define FPGA_ID_MEA2100_STG                  0x00000003
#define FPGA_ID_HS_MULTIWELL                 0x00000004
#define FPGA_ID_IF_MULTIWELL                 0x00000005
#define FPGA_ID_TBSI_DACQ_IF                 0x00000006
#define FPGA_ID_TBSI_DACQ_HS                 0x00000007
#define FPGA_ID_CMOS_MEA_IF                  0x00000008
#define FPGA_ID_CMOS_MEA_HS                  0x00000009
#define FPGA_ID_MEA2100_MW_IFB2              0x0000000A
#define FPGA_ID_ME2100_IFB                   0x0000000B
#define FPGA_ID_ME2100_InvivoSCU             0x0000000C
#define FPGA_ID_ME2100_32_XILINX_HS          0x0000000D
#define FPGA_ID_MEA2100_256_IF               0x0000000E
#define FPGA_ID_MEA2100_256_HS               0x0000000F
#define FPGA_ID_W2100_IF                     0x00000010
#define FPGA_ID_W2100_REC                    0x00000011
#define FPGA_ID_W2100_REC_ANALOG             0x00000012
#define FPGA_ID_MEA2100MINI60_PIC_ICE40_HS   0x00000013
#define FPGA_ID_MEA2100BETASCREEN_HS         0x00000014
#define FPGA_ID_ME2100UPA32_HS               0x00000015
#define FPGA_ID_MULTIWELL_MINI_HS            0x00000016
#define FPGA_ID_MEA2100MINI120_HS            0x00000017
#define FPGA_ID_MEA2100MINI60_ECP5_HS        0x00000018
#define FPGA_ID_ECUBE_HS                     0x00000019
#define FPGA_ID_ME2100_InvitroSCU            0x0000001C
#define FPGA_ID_ME2100_32_PIC_ICE40_HS       0x0000001D
#define FPGA_ID_ME2100_GRAPHENE_16_32_HS     0x0000001E
#define FPGA_ID_GRAPHENE_FLAGSHIP_CORE_2_HS  0x0000001F
#define FPGA_ID_WHOLE_CELL_PATCH_HS          0x00000020
#define FPGA_ID_INTERFACEBOARD2              0x00000021
#define FPGA_ID_W2100_IFB2                   0x00000022
#define FPGA_ID_CMOS_MEA_IFB2                0x00000023
#define FPGA_ID_LIH30_USB_IF                 0x00000041
#define FPGA_ID_LIH30_ADC_CTRL               0x00000042
#define FPGA_ID_USSING_RAIL                  0x00000050
#define FPGA_ID_USSING_CHAMBER               0x00000051
#define FPGA_ID_IFB2_GOLDEN                  0x000000FD
#define FPGA_ID_IFB30_GOLDEN                 0x000000FE
#define FPGA_ID_HAS_NO_HS                    0x00001000


//#ifdef __cplusplus
//class AnalogSource
//{
//public:
//#endif
//	enum AnalogSourceEnum {
//		AnalogSource_HS1,
//		AnalogSource_HS2,
//		AnalogSource_IF
//	};
//#ifdef __cplusplus
//};
//#endif



// define how a trigger is handles while the STG is running

#define STG200x_RETRIGGER_STOP    0
#define STG200x_RETRIGGER_RESTART 1
#define STG200x_RETRIGGER_IGNORE  2
#define STG200x_RETRIGGER_GATEMODE 3
#define STG200x_RETRIGGER_SINGLE  4

// flags for segmentated mode used in the STG400x:
// transfered in req_index, and not used by the STG200x

#define SEGMENTFLAGS_UPDATETRIGGER     1	// assign all channels to the triggernum which corresponds to its segment
#define SEGMENTFLAGS_DOWNLOADONLY      2    // for STG200x_SegmentSelect: switch the segment used for next download while keeping the device with the selected segment running
#define SEGMENTFLAGS_TRIGGERONLY       4    // switch the segment used for next trigger while keeping the segment for download
#define SEGMENTFLAGS_SYNCSTART         8    // switch segment used for trigger and start segment after next sweep

#define STG200x_NUM_DIGOUTMODES      10
#define STG200x_DIGOUTMODE_MONITOR             0
#define STG200x_DIGOUTMODE_MANUAL              1
#define STG200x_DIGOUTMODE_SYNCOUT1            2
#define STG200x_DIGOUTMODE_SYNCOUT2            3
#define STG200x_DIGOUTMODE_SYNCOUT3            4
#define STG200x_DIGOUTMODE_SYNCOUT4            5
#define STG200x_DIGOUTMODE_SYNCOUT5            6
#define STG200x_DIGOUTMODE_SYNCOUT6            7
#define STG200x_DIGOUTMODE_SYNCOUT7            8
#define STG200x_DIGOUTMODE_SYNCOUT8            9

// error handling analog the motusb library, see motstatus.h

#define IS_MCSUSB_STATUS(Status) ( ((Status) & 0xF0000000) == 0xA0000000 )

#define MCSUSB_EP0_MAX_IN_LENGTH 	  STG200x_PROGINFO_LENGTH

/***********************************************************************
 *
 * defines for the MEA_USB
 *
 ***********************************************************************/

/*! \cond meausb */
#define ME16_USB_CHANNELS		16
#define MEA_USB_CHANNELS        64
//#define MEA_USB_AMPLIFICATION 1000 removed this line, because this is not a global setting for all devices

#define MeaUSB_MAX_SAMPLERATE  50000
/*! \endcond */

/***********************************************************************
 *
 * defines for the OctoPot
 *
 ***********************************************************************/

/*! \cond octopot */
#define NANOBIO_CHANNELS   8
#define NANOBIO_PATTERNS  50
#define DOTRIA_CHANNELS   32
#define DOTRIA_DACS        4
/*! \endcond */

/***********************************************************************
 *
 * defines for the TerSens
 *
 ***********************************************************************/

/*! \cond tersens */
#define TER_CHANNELS      12
/*! \endcond */


/* Channel group defines */

#define INTERFACEANALOGCHANNELSGROUP 0x10
#define DSPDATACHANNELSGROUP 0x20
#define WIRELESSHEADSTAGEANALOGGROUPBASE 0x40
#define INTERFACEDIGITALCHANNELSGROUP 0x80
#define AUDIOTESTCHANNELGROUP 0xF8
#define PACKETFRAMECONTEXTGROUP 0xFF

#define ANALOG_GROUP        0x01
#define DIGITAL_GROUP       0x02
#define FRAME_CONTEXT_GROUP 0x03

/***********************************************************************/

#define WVC_VALVE_MODE_MANUAL  0
#define WVC_VALVE_MODE_DIGITAL 1
#define WVC_VALVE_MODE_ANALOG  2
#define WVC_VALVE_MODE_TABLE   3

#define WVC_DISPLAY_MODE_WORK        0
#define WVC_DISPLAY_MODE_PC          1
#define WVC_DISPLAY_MODE_SETTINGS    2
#define WVC_DISPLAY_MODE_TOUCH_TEST  3

/***********************************************************************/

#define USB_ERROR_I2C_NAK			0xfe

// Pic Robo Error Codes
#define ROBOERROR_BASE					(0xA0110000L)

//#define PIC_ROBOERROR_UNKNOWNCOMMAND		0x0000 // If a Stall PID is send without setting of UsbLastError, this is used
#define	PIC_ROBOERROR_TIMEOUT				0x0001
#define PIC_ROBOERROR_PRESSURE				0x0002
#define PIC_ROBOERROR_RANGE_EXCEEDED		0x0003
#define PIC_ROBOERROR_COMMUNICATIONTIMEOUT	0x0004
#define PIC_ROBOERROR_ANOTHER_MASTER        0x0005
#define PIC_ROBOERROR_FINDREFERENCEMETHOD   0x0006
#define PIC_ROBOERROR_NOSPEEDORACCELERATION 0x0007
#define PIC_ROBOERROR_NOENDSWITCH			0x0008
#define PIC_ROBOERROR_CANNOTESCAPEENDWITCH	0x0009
#define PIC_ROBOERROR_COMMANDALREADYINPROGRESS	0x000A
#define PIC_ROBOERROR_NOREFERENCE			0x000B
#define PIC_ROBOERROR_OVERPRESSURE			0x000C
#define PIC_ROBOERROR_PHASE0OUTOFRANGE		0x000D
#define PIC_ROBOERROR_PERISTALTIC_TIMEOUT   0x000E
#define PIC_ROBOERROR_GILSON_TIMEOUT        0x000F
#define PIC_ROBOERROR_GILSON_WRONG_ID		0x0010
#define PIC_ROBOERROR_GILSON_COMMAND_PENDING 0x0011
#define PIC_ROBOERROR_PARAMETER_NOT_ALLOWED 0x0012
#define PIC_ROBOERROR_STATECHANGENOTPOSSIBLE 0x0013
#define PIC_ROBOERROR_COMMANDNOTPOSSIBLE	0x0014
#define PIC_ROBOERROR_DACQ_NOT_READY		0x0015
#define PIC_ROBOERROR_NO_MORE_DATA			0x0016

// Robo current modes
#define ROBO_CURRENT_OFFMODE 0		
#define ROBO_CURRENT_BREAKMODE 1		
#define ROBO_CURRENT_STANDBYMODE 2
#define ROBO_CURRENT_REFERENCEMODE 3
#define ROBO_CURRENT_MOVEMENTMODE 4

// 
#define WPA8_ERROR_BASE					(0xA0220000L)

#define PIC_WPA8_ERR_UNKNOWN_COMMAND      0x0001
#define PIC_WPA8_ERR_HEADSTAGE_SLEEPS     0x0030
#define PIC_WPA8_ERR_HEADSTAGE_TIMEOUT 	  0x0031
#define PIC_WPA8_ERR_BUSTIMEOUT           0x0032
#define PIC_WPA8_ERR_COMMANDTIMEOUT       0x0033
#define PIC_WPA8_ERR_ALREADYSTARTED		  0x0034
#define PIC_WPA8_ERR_ILLEGAL_COMMAND_WHEN_SAMPLING 0x0035
#define PIC_WPA8_ERR_SCANNING_IS_PENDING  0x0036
// 0x0037
#define PIC_WPA8_ERR_ENABLE_CHECKSUM_RESULT 0x0038
// 0x0039 reserved
// 0x003A reserved
// 0x003B reserved

#define PIC_WPA8_ERR_ANSWER_PENDING 0x0099

#endif

