include $(CSL3X_ROOT_DIR)\src\common\build\Makefile.inc
MODULE  = tcp2

#To overide the compilation of CSL_tcp2GetBaseAddress
BADD_C_FILE=
BADD_OBJ_FILE=

include $(CSL3X_ROOT_DIR)\src\common\build\Makefile
