include $(CSL3X_ROOT_DIR)\src\common\build\Makefile.inc
MODULE  = tsc

#to override the csl3x getBaseAddress functions
BADD_C_FILE=
BADD_OBJ_FILE=

include $(CSL3X_ROOT_DIR)\src\common\build\Makefile
